[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate=lib/solmate/src/',
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256

solc_version = "0.8.19"

[profile.ci]
sizes = true
ignored_contracts = ["VRFCoordinatorV2_5Mock"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
